INSERT INTO territorialidades (nome) VALUES ('Brasil');
INSERT INTO territorialidades (nome) VALUES ('Acre');
INSERT INTO territorialidades (nome) VALUES ('Alagoas');
INSERT INTO territorialidades (nome) VALUES ('Amapá');
INSERT INTO territorialidades (nome) VALUES ('Amazonas');
INSERT INTO territorialidades (nome) VALUES ('Bahia');
INSERT INTO territorialidades (nome) VALUES ('Ceará');
INSERT INTO territorialidades (nome) VALUES ('Distrito Federal');
INSERT INTO territorialidades (nome) VALUES ('Espírito Santo');
INSERT INTO territorialidades (nome) VALUES ('Goiás');
INSERT INTO territorialidades (nome) VALUES ('Maranhão');
INSERT INTO territorialidades (nome) VALUES ('Mato Grosso do Sul');
INSERT INTO territorialidades (nome) VALUES ('Mato Grosso');
INSERT INTO territorialidades (nome) VALUES ('Minas Gerais');
INSERT INTO territorialidades (nome) VALUES ('Paraíba');
INSERT INTO territorialidades (nome) VALUES ('Paraná');
INSERT INTO territorialidades (nome) VALUES ('Pará');
INSERT INTO territorialidades (nome) VALUES ('Pernambuco');
INSERT INTO territorialidades (nome) VALUES ('Piauí');
INSERT INTO territorialidades (nome) VALUES ('Rio de Janeiro');
INSERT INTO territorialidades (nome) VALUES ('Rio Grande do Norte');
INSERT INTO territorialidades (nome) VALUES ('Rio Grande do Sul');
INSERT INTO territorialidades (nome) VALUES ('Rondônia');
INSERT INTO territorialidades (nome) VALUES ('Roraima');
INSERT INTO territorialidades (nome) VALUES ('Santa Catarina');
INSERT INTO territorialidades (nome) VALUES ('São Paulo');
INSERT INTO territorialidades (nome) VALUES ('Sergipe');
INSERT INTO territorialidades (nome) VALUES ('Tocantins');
INSERT INTO territorialidades (nome) VALUES ('RM Belém');
INSERT INTO territorialidades (nome) VALUES ('RM Belo Horizonte');
INSERT INTO territorialidades (nome) VALUES ('RM Curitiba');
INSERT INTO territorialidades (nome) VALUES ('RM Florianópolis');
INSERT INTO territorialidades (nome) VALUES ('RM Fortaleza');
INSERT INTO territorialidades (nome) VALUES ('RM Goiânia');
INSERT INTO territorialidades (nome) VALUES ('RM Grande São Luís');
INSERT INTO territorialidades (nome) VALUES ('RM Grande Teresina');
INSERT INTO territorialidades (nome) VALUES ('RM Grande Vitória');
INSERT INTO territorialidades (nome) VALUES ('RM Maceió');
INSERT INTO territorialidades (nome) VALUES ('RM Manaus');
INSERT INTO territorialidades (nome) VALUES ('RM Natal');
INSERT INTO territorialidades (nome) VALUES ('RM Porto Alegre');
INSERT INTO territorialidades (nome) VALUES ('RM Recife');
INSERT INTO territorialidades (nome) VALUES ('RM Rio de Janeiro');
INSERT INTO territorialidades (nome) VALUES ('RM Salvador');
INSERT INTO territorialidades (nome) VALUES ('RM São Paulo');
INSERT INTO territorialidades (nome) VALUES ('RM Vale do Rio Cuiabá');